In [3]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2026.2.25)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.4.4)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.5.1)

In [8]:
!mkdir -p ~/.kaggle
!echo '{"username":"fibbanachi", "key":"KGAT_84d5ad1de61ad1ff9a107a0ede3ec75f"}'> ~/.kaggle/kaggle.json
!chmod 600 ~/.kaggle/kaggle.json

In [11]:
!kaggle datasets list

ref                                                         title                                                  size  lastUpdated                 downloadCount  voteCount  usabilityRating
----------------------------------------------------------  -----------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
dmahajanbe23/bmw-global-automotive-sales                    BMW Global Automotive Sales                           55017  2026-02-22 18:18:38.170000           3959         75  1.0
thuandao/superstore-sales-analytics                         SuperStore Sales Analytics                          2283450  2026-03-06 12:31:25.800000            817         24  1.0
alitaqishah/ai-jobs-market-2025-2026-salaries               AI Jobs Market 2025-2026 | Salaries                   62669  2026-03-06 04:06:56.600000            447         28  1.0
suhanigupta04/student-placement-prediction-dataset          Student Placement Prediction Dataset                1873115  2026-03-02 07:41:44.213000           1135         31  1.0
shree0910/online-vs-in-store-shopping-behaviour-dataset     Online vs In-Store Shopping Behaviour Dataset        354896  2026-02-18 08:16:20.137000           1925         43  1.0
aliiihussain/amazon-sales-dataset                           Amazon_Sales_Dataset                                1297759  2026-02-01 11:37:12.353000          11832        178  1.0
likithagedipudi/starbucks-customer-ordering-patterns        Starbucks Customer Ordering Patterns                2789356  2026-02-28 04:03:20.867000           1614         42  1.0
grandmaster07/student-exam-performance-dataset-analysis     Student Exam Performance Dataset Analysis             96178  2026-02-10 09:47:13.350000           2828         67  1.0
mafaqbhatti/top-100-cities-by-population-2026               Top 100 Cities by Population 2026                      2067  2026-03-03 04:49:23.227000            722         32  1.0
neurocipher/digital-distraction-vs-academic-performance     Digital Distraction vs Academic Performance          454078  2026-03-04 15:28:44.953000            419         22  1.0
algozee/heart-decices                                       Heart Disease Prediction Using Machine Learning    10070453  2026-02-22 17:32:58.757000           2100         61  1.0
meharshanali/middle-east-economy-and-oil-prices-19902024    🌍 Middle East Economy & Oil Prices (1990–2024)        32716  2026-03-03 07:08:55.367000            754         25  1.0
meharshanali/student-dropout-prediction-dataset             📄 Student Dropout Prediction Dataset                 260641  2026-02-22 07:45:08.980000           2171         41  1.0
krupalpatel07/gold-price-dynamics                           Gold Price Dynamics                                   85982  2026-03-03 05:42:46.960000            704         26  1.0
likithagedipudi/war-economic-and-livelihood-impact-dataset  War Economic & Livelihood Impact Dataset            6395727  2026-03-02 03:14:17.083000            886         32  1.0
litonislam/amazon-sales-analysis-cleaned-data               Amazon Sales Analysis- Cleaned Data                 1519934  2026-02-23 13:40:35.507000           1436         39  1.0
rakesh630/global-student-placement-2025-dataset             Global Student Placement & Salary Dataset            494191  2026-02-26 18:55:58.870000            540         31  1.0
algozee/student-productivity-and-behavior-dataset-20k       Student Productivity & Behavior Dataset (20K)        631991  2026-02-24 08:45:04.133000           1453         61  1.0
syedaeman2212/apple-prices-dataset                          Apple Prices Dataset                                   9767  2026-03-05 16:21:38.527000            327         29  1.0
nudratabbas/ai-worker-burnout-and-attrition-risk-dataset    AI Worker Burnout & Attrition Risk Dataset            41637  2026-02-28 10:12:33.790000            641         29  1.0

In [17]:
import pandas as pd
import numpy as np
import zipfile

In [13]:
!kaggle datasets download -d yasserh/titanic-dataset

Dataset URL: https://www.kaggle.com/datasets/yasserh/titanic-dataset
License(s): CC0-1.0
Downloading titanic-dataset.zip to /content
  0% 0.00/22.0k [00:00<?, ?B/s]
100% 22.0k/22.0k [00:00<00:00, 53.3MB/s]

In [21]:
with zipfile.ZipFile('titanic-dataset.zip', 'r') as zip_ref:
    zip_ref.extractall()
!ls -la /content/

total 100
drwxr-xr-x 1 root root  4096 Mar  9 09:24 .
drwxr-xr-x 1 root root  4096 Mar  9 09:00 ..
drwxr-xr-x 4 root root  4096 Jan 16 14:24 .config
drwxr-xr-x 1 root root  4096 Jan 16 14:24 sample_data
-rw-r--r-- 1 root root 61194 Mar  9 09:27 Titanic-Dataset.csv
-rw-r--r-- 1 root root 22564 Dec 24  2021 titanic-dataset.zip

In [22]:
df = pd.read_csv('/content/Titanic-Dataset.csv')

In [28]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [29]:
df.isna().mean()

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.002245
dtype: float64

In [38]:
df_age = df[df['Age'].isna() == False].groupby('Age')[['Survived', 'Pclass', 'Ticket','Sex', 'Parch', 'Fare']].count()

In [39]:
df_age

       Survived  Pclass  Ticket  Sex  Parch  Fare
Age
0.42          1       1       1    1      1     1
0.67          1       1       1    1      1     1
0.75          2       2       2    2      2     2
0.83          2       2       2    2      2     2
0.92          1       1       1    1      1     1
...         ...     ...     ...  ...    ...   ...
70.00         2       2       2    2      2     2
70.50         1       1       1    1      1     1
71.00         2       2       2    2      2     2
74.00         1       1       1    1      1     1
80.00         1       1       1    1      1     1

[88 rows x 6 columns]

In [43]:
df['Age_cut'] = pd.cut(df['Age'], bins=10)

In [44]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_cut
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,"(16.336, 24.294]"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"(32.252, 40.21]"
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"(24.294, 32.252]"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,"(32.252, 40.21]"
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,"(32.252, 40.21]"

In [57]:
df_age = df[df['Age'].isna() == False].groupby('Age_cut')[['Survived', 'Pclass', 'Parch', 'Fare']].median()

/tmp/ipykernel_186/2022785945.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_age = df[df['Age'].isna() == False].groupby('Age_cut')[['Survived', 'Pclass', 'Parch', 'Fare']].median()

In [58]:
df_age

                  Survived  Pclass  Parch     Fare
Age_cut
(0.34, 8.378]          1.0     3.0    1.0  26.2500
(8.378, 16.336]        0.0     3.0    1.0  20.3875
(16.336, 24.294]       0.0     3.0    0.0   9.5000
(24.294, 32.252]       0.0     3.0    0.0  13.0000
(32.252, 40.21]        0.0     2.0    0.0  21.0000
(40.21, 48.168]        0.0     2.0    0.0  26.0000
(48.168, 56.126]       0.0     1.0    0.0  30.5000
(56.126, 64.084]       0.0     1.0    0.0  28.1250
(64.084, 72.042]       0.0     1.0    0.0  26.5500
(72.042, 80.0]         0.5     2.0    0.0  18.8875

In [69]:
df[df['Age'].isna() == True].groupby('Pclass').count()

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_cut
Pclass,,,,,,,,,,,,
1,30,30,30,30,0,30,30,30,30,16,30,0
2,11,11,11,11,0,11,11,11,11,1,11,0
3,136,136,136,136,0,136,136,136,136,2,136,0

In [73]:
df[df['Age'].isna() == False].groupby('Pclass')['Age'].median()

Pclass
1    37.0
2    29.0
3    24.0
Name: Age, dtype: float64

In [79]:
df['Age'] = df['Age'].fillna(df['Pclass'].map({1: 37, 2: 29, 3: 24}))

In [80]:
df.isna().mean()

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.000000
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.002245
Age_cut        0.198653
dtype: float64

In [81]:
df[df['Embarked'].isna() == True].groupby('Pclass').count()

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_cut
Pclass,,,,,,,,,,,,
1,2,2,2,2,2,2,2,2,2,2,0,2

In [86]:
df[df['Embarked'].isna() == False].groupby('Pclass')['Embarked'].agg(pd.Series.mode)

Pclass
1    S
2    S
3    S
Name: Embarked, dtype: object

In [91]:
df.dtypes

PassengerId       int64
Survived          int64
Pclass            int64
Name             object
Sex              object
Age             float64
SibSp             int64
Parch             int64
Ticket           object
Fare            float64
Cabin            object
Embarked         object
Age_cut        category
dtype: object

In [92]:
df['Embarked'] = df['Embarked'].fillna('S')

In [94]:
df.isna().mean()

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.000000
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.000000
Age_cut        0.198653
dtype: float64

In [95]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.5 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [97]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    f1_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)
from catboost import CatBoostClassifier
from tqdm import tqdm

In [99]:
train, test = train_test_split(df, train_size = 0.6, random_state = 42)

In [100]:
train, val = train_test_split(train, train_size = 0.8, random_state = 42)

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    object
 12  Age_cut      714 non-null    category
dtypes: category(1), float64(2), int64(5), object(5)
memory usage: 85.0+ KB

In [109]:
df['Embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [116]:
X = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch','Fare','Embarked']
cat_features = ['Sex', 'Pclass', 'Embarked', 'SibSp', 'Parch']
Y = ['Survived']

In [121]:
model = CatBoostClassifier(cat_features=cat_features,
                          eval_metric='AUC',
                          random_seed=42,
                          verbose=100)

In [122]:
model.fit(train[X],train[Y], eval_set=(val[X],val[Y]))

Learning rate set to 0.025682
0:	test: 0.8137255	best: 0.8137255 (0)	total: 63.4ms	remaining: 1m 3s
100:	test: 0.8437029	best: 0.8482278 (89)	total: 770ms	remaining: 6.86s
200:	test: 0.8463424	best: 0.8482278 (89)	total: 1.06s	remaining: 4.22s
300:	test: 0.8425716	best: 0.8512443 (215)	total: 1.45s	remaining: 3.36s
400:	test: 0.8293741	best: 0.8512443 (215)	total: 2.3s	remaining: 3.44s
500:	test: 0.8210784	best: 0.8512443 (215)	total: 3.34s	remaining: 3.32s
600:	test: 0.8176848	best: 0.8512443 (215)	total: 3.69s	remaining: 2.45s
700:	test: 0.8112745	best: 0.8512443 (215)	total: 4.07s	remaining: 1.73s
800:	test: 0.8071267	best: 0.8512443 (215)	total: 4.42s	remaining: 1.1s
900:	test: 0.8059955	best: 0.8512443 (215)	total: 4.78s	remaining: 525ms
999:	test: 0.8041101	best: 0.8512443 (215)	total: 5.14s	remaining: 0us

bestTest = 0.8512443439
bestIteration = 215

Shrink model to first 216 iterations.

CatBoostClassifier(cat_features=['Sex', 'Pclass', 'Embarked', 'SibSp', 'Parch'], eval_metric='AUC', random_seed=42, verbose=100)

In [125]:
y_pred_val = model.predict(val[X])

In [129]:
y_pred_proba = model.predict_proba(val[X])[:, 1]

In [126]:
y_valid = val[Y]

In [130]:
print("F1-score:", f1_score(y_valid, y_pred_val))
print("ROC-AUC:", roc_auc_score(y_valid, y_pred_proba))
print("\nПолный отчёт:")
print(classification_report(y_valid, y_pred_val))
print("Матрица ошибок:")
print(confusion_matrix(y_valid, y_pred_val))

F1-score: 0.6451612903225806
ROC-AUC: 0.8512443438914027

Полный отчёт:
              precision    recall  f1-score   support

           0       0.77      0.96      0.86        68
           1       0.87      0.51      0.65        39

    accuracy                           0.79       107
   macro avg       0.82      0.73      0.75       107
weighted avg       0.81      0.79      0.78       107

Матрица ошибок:
[[65  3]
 [19 20]]

In [133]:
y_test = test[Y]

In [132]:
y_pred_test = model.predict(test[X])

In [134]:
y_pred_proba = model.predict_proba(test[X])[:, 1]

In [136]:
print("F1-score:", f1_score(y_test, y_pred_test))
print("ROC-AUC:", roc_auc_score(y_test, y_pred_proba))
print("\nПолный отчёт:")
print(classification_report(y_test, y_pred_test))
print("Матрица ошибок:")
print(confusion_matrix(y_test, y_pred_test))

F1-score: 0.7166666666666667
ROC-AUC: 0.869927107959023

Полный отчёт:
              precision    recall  f1-score   support

           0       0.79      0.94      0.86       216
           1       0.87      0.61      0.72       141

    accuracy                           0.81       357
   macro avg       0.83      0.77      0.79       357
weighted avg       0.82      0.81      0.80       357

Матрица ошибок:
[[203  13]
 [ 55  86]]

In [143]:
test_kaggle = pd.read_csv('/content/test.csv')

In [144]:
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch','Fare','Embarked']

In [145]:
X_kaggle = test_kaggle[features].copy()

In [146]:
X_kaggle['Age'] = X_kaggle['Age'].fillna(X_kaggle['Pclass'].map({1: 37, 2: 29, 3: 24}))
X_kaggle['Embarked'] = X_kaggle['Embarked'].fillna('S')

In [147]:
predictions = model.predict(X_kaggle)
submission = pd.DataFrame({
    'PassengerId': test_kaggle.PassengerId,
    'Survived': predictions.astype(int)
})
submission.to_csv('submission.csv', index=False)

In [148]:
importances = model.feature_importances_

feature_importance = pd.DataFrame({
    'feature': features,
    'importance': importances
}).sort_values('importance', ascending=False)

print(feature_importance)

    feature  importance
1       Sex   46.774885
0    Pclass   18.632347
6  Embarked    9.072464
2       Age    7.462988
5      Fare    6.719727
4     Parch    6.180103
3     SibSp    5.157487

Обучение на другой модели (случайный лес)

In [150]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

In [151]:
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch','Fare','Embarked']
cat_features = ['Sex', 'Embarked']

In [153]:
Y_train = train['Survived']
X_train = train[features].copy()

In [156]:
X_train_split, X_val, y_train_split, y_val = train_test_split(
    X_train, y_train,
    train_size=0.8,
    random_state=42,
    stratify=y_train  # Важно для Titanic!
)

In [157]:
le_sex = LabelEncoder()
le_embarked = LabelEncoder()

X_train_split['Sex'] = le_sex.fit_transform(X_train_split['Sex'])
X_val['Sex'] = le_sex.transform(X_val['Sex'])

X_train_split['Embarked'] = le_embarked.fit_transform(X_train_split['Embarked'])
X_val['Embarked'] = le_embarked.transform(X_val['Embarked'])

In [159]:
model = RandomForestClassifier(n_estimators=200, max_depth=7, random_state=42)
model.fit(X_train_split, y_train_split)

RandomForestClassifier(max_depth=7, n_estimators=200, random_state=42)

In [160]:
y_pred_train = model.predict(X_train_split)
y_pred_val = model.predict(X_val)

In [163]:
print("\n=== CLASSIFICATION REPORT (Val) ===")
print(classification_report(y_val, y_pred_val))

=== CLASSIFICATION REPORT (Val) ===
              precision    recall  f1-score   support

           0       0.83      0.92      0.88        53
           1       0.85      0.70      0.77        33

    accuracy                           0.84        86
   macro avg       0.84      0.81      0.82        86
weighted avg       0.84      0.84      0.83        86

In [164]:
y_prob_train = model.predict_proba(X_train_split)[:, 1]
y_prob_val = model.predict_proba(X_val)[:, 1]

In [166]:
print("=== ПОЛНЫЙ ОТЧЕТ (Validation) ===")
print(f"F1-score:  {f1_score(y_val, y_pred_val):.3f}")
print(f"ROC-AUC:   {roc_auc_score(y_val, y_prob_val):.3f}")
print()

=== ПОЛНЫЙ ОТЧЕТ (Validation) ===
F1-score:  0.767
ROC-AUC:   0.851

In [167]:
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch','Fare','Embarked']

# Предобработка test (ТЕ ЖЕ действия!)
X_kaggle = test_kaggle[features].copy()

# Заполни пропуски (как в train)
X_kaggle['Age'] = X_kaggle['Age'].fillna(
    X_kaggle['Pclass'].map({1: 37, 2: 29, 3: 24})
)
X_kaggle['Fare'] = X_kaggle['Fare'].fillna(13)
X_kaggle['Embarked'] = X_kaggle['Embarked'].fillna('S')

# ТОТ ЖЕ LabelEncoder из train!
X_kaggle['Sex'] = le_sex.transform(X_kaggle['Sex'])
X_kaggle['Embarked'] = le_embarked.transform(X_kaggle['Embarked'])

In [168]:
predictions = model.predict(X_kaggle)

# Создай submission
submission2 = pd.DataFrame({
    'PassengerId': test_kaggle['PassengerId'],
    'Survived': predictions.astype(int)
})

# СОХРАНИ
submission2.to_csv('submission2.csv', index=False)